chest= [
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1298_0_thumb.jpg",
      "title": "Bench Press",
      "videos": "",
      "Sort": "The mighty bench press is a great exercise for building a powerful chest. The bench press is one of the power exercises, known to be very effective for building body mass. Learning how to do a proper bench press is well worth the effort.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1298_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Most gyms have benches specifically designed for the bench press and its variations. Lie flat on one of these benches with your feet firmly on the ground. The bar should be resting on the bench's rack.  Lift the bar off the rack and hold it above your chest in the starting position. Lower the bar down until it touches your chest. Hold this position briefly and make sure you have complete control of the bar. Now raise the bar up to the starting postion.  Return the bar to the rack after you've completed your set.",
      "tips": "The width of your grip on the bar will change the focus of the bench press. A medium grip is most common. This is slightly wider than shoulder-width apart. It's usually marked on the bar.  Having a spotter to help you with the bench press is essential. A competitive, motivating spotter is one of the most valuable assets you can find.  Choose a weight that is challenging and allows you to maintain proper form. Improper form is less effective and could result in an injury. Use a slow controlled motion and never lock your elbows.",
      "warning": "",
      "id": 1,
      "bigImg1":"https://www.gymwolf.com/images/exercises/1298_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1276_0_thumb.jpg",
      "title": "Bench Press Machine",
      "videos": "",
      "Sort": "This is a primary exercise for the Pectorals (chest muscles). Many people prefer this exercise to the standard Bench Press because if offers more stability for people new to exercise.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1276_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"",
      "steps": "Adjust the machine so that you are sitting with the bars at chest height.  Place your hands on the bars and place your feet on the foot rest.  Press out, extending your arms as far as possible in a steady motion.  Pause for a moment and then return slowly to starting position.",
      "tips": "",
      "warning": "",
      "id": 2,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1276_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1296_0_thumb.jpg",
      "title": "Bench Press With Bands",
      "videos": "",
      "Sort": "A bench press variation that uses bands as resistance. The resistance comes from a slightly different angle so will target a different area of your pectorals.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1296_0.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Run a resistance band under the legs of the top side of a bench. Attach handles to the resistance cable. Lie down flat on the bench and grip one handle in each hand. Rest your arms with your elbows bent and out to your side. Your hands should be at chest level.  Push the handles up towards the ceiling until your hands are as high as they can go. Hold the top position for a moment then return your hands to the starting position.",
      "tips": "Don't lock your elbows at the top of this exercise.",
      "warning": "",
      "id": 3,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1296_1.jpg",
      "video":"",
      "photo":"",

    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1273_0_thumb.jpg",
      "title": "BOSU Ball Push-Ups",
      "videos": "",
      "Sort": "This exercise combines a standard Push Up with a half round exercise Dome to become a Core focused exercise. Core exercises strengthen the abdominal and back muscles.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1273_0.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Place the Dome flat side down on the floor.  Kneel on the floor with your arms fully extended on the dome, and body straight.  Keeping your abs drawn in and your body straight, lower your chest to the Dome.  Pause for a moment and then return to starting position.",
      "tips": "This is a difficult exercise to master. Beginners may want to start on your knees with your feet off the ground so you are rocking into the Push Up.",
      "warning": "",
      "id": 4,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1273_1.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1293_0_thumb.jpg",
      "title": "Butterfly Machine",
      "videos": "",
      "Sort": "The butterfly machine is a simple way to target your chest. This is a machine exercise, so it's very easy to do.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1293_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Sit on the machine with your back flat. Adjust the height of the seat so that the pads of the machine are at your chest height. put your forearms against the pads.  Push the pads together as you squeeze your chest. Push until the pads meet in the middle. Hold this position for a moment then return to the starting position.",
      "tips": "Focus on using your chest for this exercise. You should be squeezing from the inner part of your chest, not pushing with your biceps or shoulders.",
      "warning": "",
      "id": 5,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1293_0.jpg",
      "video":"",
      "photo":"",

    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1292_0_thumb.jpg",
      "title": "Cable Crossover",
      "videos": "",
      "Sort": "The cable crossover is a good exercise for targeting your inner chest.  It does require that you have 2 cable machines facing each other, but this is a common setup in most gyms.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1292_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Attach handles to the higher pulleys of both cable machines. Stand between the two machines with your legs and waist slightly bent. Grip the handles of the pulleys with your palms facing down and your arms out to your sides.  Slowly pull the handles down towards the floor until they touch or cross over in front of you. Hold this position for a few moments then return to the starting position.",
      "tips": "When your arms are in front of you, contract your pectorals for a moment to make this exercise even more effective.",
      "warning": "",
      "id": 6,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1292_0.jpg",
      "video":"",
      "photo":"",

    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1286_0_thumb.jpg",
      "title": "Chest Dips",
      "videos": "",
      "Sort": "The chest dip is a variation of the tricep dip that focuses more on your chest. Even though it uses a dip machine, it is a body weight only exercise.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1286_1.jpg",
      "muscleGroup": "",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Grip the bars of the dip bar (ask for assistance if you're not sure which machine this is) and push yourself up to the starting position. Your arms should be straight and fairly close to your body. Keep your knees bent so that your feet never touch the ground.  Slowly lower your body, leading with your chest as you go down. Your chest should start pointing down towards the ground at a 45 degree angle. Lower your body until you feel a stretch in your chest and shoulders, then begin to slowly raise your body up again.",
      "tips": "If you can't quite manage this exercise then you can get a spotter to hold on to your feet and assist you. If the exercise is too easy, then you can wear a weighted belt.  Try not to lock your elbows in the starting position.  Keep your abs tight and back straight throughout this exercise.",
      "warning": "",
      "id": 7,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1286_1.jpg",
      "video":"",
      "photo":"",

    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1269_0_thumb.jpg",
      "title": "Close or Wide Push Ups",
      "videos": "",
      "Sort": "These are variations on Push Ups, one of the best exercise for muscles of the chest (pectorals), arms (bicep and triceps) and core development. The core muscles are the rectus abdomen and obliques which support the spine.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1269_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "For a Close Grip Push Up lay face down on the floor, or a mat, with your feet together curled slightly so you rise on the ball of your feet.  Place you hands close together so your thumbs and index fingers form a triagle on the floor.  Draw your abs in.  Inhale as you raise your body up till your arms are straight.  Keep your head and neck level with your body (dont look up or down) and dont allow your back to rise or fall.  Exhale out as you lower your body back to the ground.  For a Wide Grip Push Up move your hands out to a position slightly wider than your shoulders.",
      "tips": "A close grip works more of the inner pectorals and a wide grip works more of the outer pectorals.",
      "warning": "",
      "id": 8,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1269_0.jpg",
      "video":"",
      "photo":"",

    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1289_0_thumb.jpg",
      "title": "Decline Bench Press",
      "videos": "",
      "Sort": "The decline bench press is a variation of the bench press performed on a incline bench. It targets the lower part of your chest.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1289_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Lie on a decline bench so that your head is lower than your feet. Grip a barbell with an overhand grip, your palms facing towards your feet and your hands slightly wider than shoulder-width apart. Hold the bar directly above your chest.  Slowly lower the bar all the way until it meets your chest. Then, raise the bar straight back up to the starting position.",
      "tips": "Concentrate on using your chest for this bench press. You should feel as it the lifting is coming from your elbows.",
      "warning": "",
      "id": 9,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1289_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1259_0_thumb.jpg",
      "title": "Decline Chest Press",
      "videos": "",
      "Sort": "This is an exercise for the lower portion of the Pectorals (chest muscles). Many people prefer this exercise to the Barbell or Dumbbell decline Press because if offers more stability for people new to exercise.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1259_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Adjust the seat of the machine so that the handles are near the lower portion of your chest.  Slowly press the handles forward until your hands are fully extended, do not lock your elbows.  Pause for a moment and then with a controlled movement lower your hands back to starting position.",
      "tips": "Keep your shoulders and lower back against the bench at all times during this exercise.",
      "warning": "",
      "id": 10,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1259_0.jpg",
      "video":"",
      "photo":"",

    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1288_0_thumb.jpg",
      "title": "Decline Dumbbell Bench Press",
      "videos": "",
      "Sort": "The dumbbell incline bench press targets your lower chest. It incorporates your stability muscles more than the standard incline bench press.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1288_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Lie on a decline bench so that your head is lower than your feet. Grip a pair of dumbbells with an overhand grip, your palms facing towards your feet. Hold the dumbbells directly above your chest so that their inner edges are touching.  Slowly lower the dumbbells all the way until they are inline with the top of your chest. Then, raise them straight up to the starting position.",
      "tips": "The dumbbell bench press puts more focus on your stabilizing muscles. You could alternate between the dumbbell and the barbell versions of the exercise to get the benefits of both exercise types.",
      "warning": "",
      "id": 11,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1288_0.jpg",
      "video":"",
      "photo":"",

    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1285_0_thumb.jpg",
      "title": "Dumbbell Bench Press",
      "videos": "",
      "Sort": "The dumbbell bench press is a great alternative to the standard bench press. You can do the dumbbell bench press without relying on a spotter. It's also good to alternate between the standard bench press and the dumbbell bench press so your muscles don't get too used to either.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1285_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Pick up your dumbbells and hold them at your sides. Then sit on the edge of your flat bench. Sit back as you use your thighs to lush the weights up to their starting position.  Start with your arms holding dumbbells about an inch higher than your chest. The dumbbells should be in line with the middle of your chest so that your arms are comfortably out to the sides.  Slowly push the dumbbells up. Focus on using your chest and triceps to push most of the weight. Stop when your arms are straight and the dumbbells are directly above your chest. Don't clank the dumbbells together or spin them around when you get to the top.  Next, slowly lower the dumbbells. Don't let gravity do the work. You should be resisting gravity all the way down. The rep ends when the dumbbells are back to 1 inch above your chest.",
      "tips": "Breathe comfortably and deeply. Especially while you're pushing the dumbbells up.",
      "warning": "",
      "id": 12,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1285_0.jpg",
       "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1287_0_thumb.jpg",
      "title": "Dumbbell Decline Flys",
      "videos": "",
      "Sort": "Decline dumbbell flys target the inner part of your lower chest. They also stretch your chest and biceps, making them a good addition to any workout program.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1287_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Lie flat on a decline bench with your head lower than your feet. Hold a dumbbell in each hand with your elbows slightly bent and your arms out to your sides. Your elbows should be facing straight down towards the ground and you should feel a stretch in your chest and biceps.  Squeeze your chest to bring the dumbbells up along an arc towards the center, directly above your chest. Hold this position for a moment and squeeze your chest. Next, lower the dumbbells back to their starting position at your sides.",
      "tips": "You can add a slight twist at the top of the fly. This means that instead of touching together the dumbbell's sides, you touch their inner sides together.",
      "warning": "",
      "id": 13,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1285_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1284_0_thumb.jpg",
      "title": "Dumbbell Flys",
      "videos": "",
      "Sort": "The dumbbell fly targets your pectorals with far more focus than the standard dumbbell bench press. You're keeping your arms relatively straight throughout the exercise so you wont use your triceps as much. It also focuses more on the inner part of your pecs.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1284_0.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Lie on a flat bench with your arms out to your sides. Your elbows should be pointing down to the ground and your palms up to the ceiling. You should hold the dumbbells at roughly the height of your shoulders.  Focus on using your chest to bring your arms up until the dumbbells are directly above your chest. Your biceps and triceps should just be stabilizing your arms. You shouldn't be using them for any of the lifting.  In the top position your elbows should be facing outwards and your palms facing inwards towards each other.  Hold the dumbbells briefly at the top then slowly lower them. Again, focus on using your chest to control the downwards motion.",
      "tips": "This is a very focused and targeted exercise. Concentrate on using your chest to drive the majority of the dumbbell fly.  As usual, remember to breathe comfortably. Don't hold your breath.",
      "warning": "",
      "id": 14,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1284_1.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1308_0_thumb.jpg",
      "title": "Dumbbell incline bench press",
      "videos": "",
      "Sort": "This variation of a bench press is a great workout for your upper chest.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1308_0.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Start by setting up a bench so that it has a 30 degree incline. Place 2 dumbbells by your feet then sit in the bench.  Bring the dumbbells to their starting position just above your chest. Your elbows should be bent so that your forearms are facing directly upwards.  Push the dumbbells straight up. Focus on using your chest for this exercise. You should feel as if the lifting is coming from your elbows. Raise the dumbbells as high as you can without locking your elbows, then slowly lower them to the starting position.",
      "tips": "Depending on the weight you're using, it might be difficult to get into the starting position for this exercise. Ideally you should have a spotter to help you but if you can't find someone who's willing, then you'll need to \"kick\" the weights into the starting position. Do this by resting the dumbbells on your thighs then push with your thighs as you pull with your arms to get the dumbbells up.",
      "warning": "",
      "id": 15,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1308_1.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1283_0_thumb.jpg",
      "title": "Flat Bench Cable Flys",
      "videos": "",
      "Sort": "The Flat Bench Cable Fly targets your chest using the fly motion. It's similar to a cable crossover. The difference is this exercise allows you to support your back on the bench.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1283_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Place a bench between 2 cable machines. Position the bench so that when you lie on it, your shoulders are in line with the pulleys of the cable machine. Grab one handle in each hand then sit on the edge of the bench. Slowly lean back to get yourself into the starting position.  Your arms should be out to your sides with your elbows pointing down towards the ground. You should have a slight bend in your elbows.  Slowly lift handles up above your chest. Don't bend your elbows or straighten your elbows as you lift the handles. Continue until your hands are directly above your shoulders. Hold this position for a moment.  Next, lower the handles down to your starting position.",
      "tips": "Start on a low weight then work your way up. This exercise is intense and could cause shoulder injuries if you aren't careful.  As always, remember to breathe while you're doing the flat bench cable fly.",
      "warning": "",
      "id": 16,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1283_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1282_0_thumb.jpg",
      "title": "Front Raise And Pullover",
      "videos": "",
      "Sort": "This is a combination exercise that works the chest, shoulder and arms. It can also give you a good assisted stretch.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1282_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"",
      "steps": "Lie on a flat bench and grasp a barbell using a medium grip (about 15 apart).  Place the barbell on your upper thighs and lock your arms straight.  Draw your abs in and keeping your back flat on the bench, raise your arms up and in an arc over behind your head (as if you were performing a reverse pullover).  Slowly return the barbell to the starting position on your thighs.",
      "tips": "",
      "warning": "",
      "id": 17,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1282_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1281_0_thumb.jpg",
      "title": "Hammer Grip Incline Dumbbell Bench Press",
      "videos": "",
      "Sort": "The Hammer Grip Incline Bench Press is a variation of the standard Incline Dumbbell Bench Press where your palms face in towards each other.  Using a hammer grip tends to isolate the chest and helps take pressure off your shoulders.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1281_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"",
      "steps": "Lie on an incline bench with a dumbbell in each hand. Your palms should be facing in towards each other with your arms comfortably out to the side. Your arms should be at about a 45 degree angle from your body.  Raise the dumbbells up. Make sure that your palms are always facing directly towards each other. Raise the dumbbells until they are directly above your shoulders. Hold this top position for a moment then slowly lower the dumbbells.  As you lower the dumbbells concentrate on keeping the dumbbells facing towards each other. Stop when the dumbbells are about 2 inches above your chest, then repeat.",
      "tips": "",
      "warning": "",
      "id": 18,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1281_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1297_0_thumb.jpg",
      "title": "Incline Bench Press",
      "videos": "",
      "Sort": "This is a variation of the bench press that targets your upper chest by using an incline bench. It'll help give your fuller, more balanced size.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1297_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Set your bench to a 45 degree angle or find a specially designed inclined bench press bench. lie flat on the bench with your feet firmly on the floor. Grip the bar slightly wider than shoulder-width apart.  Lift the bar off the rack and hold it directly above your chest in the starting position. Lower the bar until it touches your chest, then hold it for a few moments. Finally, raise the bar up to the starting position.",
      "tips": "Use a slow, controlled motion for the incline bench press. Don't lock your elbows when you're in the starting position.",
      "warning": "",
      "id": 19,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1297_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1280_0_thumb.jpg",
      "title": "Incline Cable Flys",
      "videos": "",
      "Sort": "Cable Flyes target your upper part of your pectorals. It's similar to the standard Inline Dumbbell Flyes.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1280_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Set up a bench so that it is at a 35 to 45 degree angle. Make sure that the pulleys of the cable machine are in line with your shoulders when you're lying on the bench.  Grab the cable machine handles then sit on the bench. Lean back carefully. In the starting position your arms should be out to your side. Your elbows should be slightly bent and pointing at the ground.  Slowly pull on the cables, concentrate on using your chest to do the pulling. Keep on pulling until the handles are directly above you. Hold this position for a moment.  Next lower the handles down to their orinal positions.",
      "tips": "Make sure that the bend in your elbows when you're in the final position is similar to the bend in your elbows at the start.  Focus on using your chest as much as possible for the incline flyes. Your arms and especially your triceps shouldn't be doing much work.",
      "warning": "",
      "id": 20,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1280_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1260_0_thumb.jpg",
      "title": "Incline Chest Press",
      "videos": "",
      "Sort": "This is an exercise for the upper portion of the Pectorals (chest muscles). Many people prefer this exercise to the Barbell or Dumbbell Incline Press because if offers more stability for people new to exercise.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1260_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Adjust the seat of the machine so that the handles are near the upper portion of your chest.  Slowly press the handles forward until your hands are fully extended, do not lock your elbows.  Pause for a moment and then with a controlled movement lower your hands back to starting position.",
      "tips": "Keep your shoulders and lower back against the bench at all times during this exercise.",
      "warning": "",
      "id": 21,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1260_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1279_0_thumb.jpg",
      "title": "Incline Flys",
      "videos": "",
      "Sort": "This is a sculpting exercise for the pectoral muscles (Chest).",
      "bigImg": "https://www.gymwolf.com/images/exercises/1279_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Lie on an incline bench set a 45 degree angle with a dumbbell in each hand.  Lift the dumbbells over your chest extending your arms fully.  Keeping a slight bend in your elbows, lower the dumbbells towards the floor in and arc like motion.  Slowly return to starting position.",
      "tips": "Keep your hips and shoulders on the bench at all times during this exercise.",
      "warning": "",
      "id": 22,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1279_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1278_0_thumb.jpg",
      "title": "Incline Flys With A Twist",
      "videos": "",
      "Sort": "This is an advanced exercise for the chest and very good for sculpting and defining when used along with bench presses. At the top of the exercise you twist your arms so that your pinky finger are facing each other.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1278_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Lie on an incline bench set a 45 degree angle with a dumbbell in each hand.  Start with the dumbbells out to the sides of your chest, parallel to the floor as you would a regular Fly.  Raise the dumbbells over your chest in and arc  At the top, turn your pinky finger in so they are facing each other.  Slowly return to starting position.",
      "tips": "Keep your hips and shoulders on the bench at all times during this exercise.  Keep a slight bend in your elbows during this exercise.",
      "warning": "",
      "id": 23,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1278_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1264_0_thumb.jpg",
      "title": "Incline Press",
      "videos": "",
      "Sort": "This is a primary exercise to build the pectorals (chest muscles).",
      "bigImg": "https://www.gymwolf.com/images/exercises/1264_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Set and incline bench at a 45 degree angle.  Start with the dumbbells at shoulder height, your arms wide and elbows pointing down to the floor.  Raise your arms up over your chest bringing the dumbbells closer together as they meet over your chest.  Slowly return the dumbbells to starting position.",
      "tips": "Place the dumbbells on your upper thigh and kick them up to starting position one a time.",
      "warning": "",
      "id": 24,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1264_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1263_0_thumb.jpg",
      "title": "Incline Smith Machine Bench Press",
      "videos": "",
      "Sort": "This is an exercise to build the pectoral muscles of the chest. This is a good exercise for beginners as the Smith Machine allows for greater control of the weights.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1263_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Place an incline bench at a 45 degree angle in the middle of the Smith Machine.  Align the bench so the bar is across the upper portion of your chest  Grasp the bar with a shoulder width grip  Unlock the bar and slowly lower the weight to your chest, do not bounce the bar on your chest.  With slow controlled movements, raise the bar back to the starting position.",
      "tips": "Keep your feet flat and your back against the bench throughout this exercise.",
      "warning": "",
      "id": 25,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1263_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1275_0_thumb.jpg",
      "title": "Neck Press",
      "videos": "",
      "Sort": "This is an advanced exercise for the chest. It is similar to a Bench Press except you keep the barbell moving over your neck not your chest.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1275_0.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"",
      "steps": "Lie on a flat bench with you feet planted firmly on the floor.  Grasp the bar a little wider than shoulder width apart.  Raise the barbell above your body and move it to the top of your chest, near your neck. This is your starting position.  Lower the bar down so it just touches the top of your chest.  Raise the bar till your arms are fully extended and your elbows are locked.  Return to starting position.",
      "tips": "",
      "warning": "",
      "id": 26,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1275_1.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1274_0_thumb.jpg",
      "title": "One Arm Bench Press",
      "videos": "",
      "Sort": "This is a very advanced exercise used mostly by body builders and power lifters. This exercise should no be done by beginners and it is recommended that someone demonstrate this exercise you and spot you while performing it.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1274_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Lie flat on a bench with your feet placed firmly on the floor and your abs drawn in.  Grasp the dumbbell in one hand and bring it up to the side of your chest, this is starting position.  Extend your arm, pressing the dumbbell up till your arm is straight and your elbow locked.  Using slow controlled movements, lower the weight to starting position.  Switch arms after completing reps with one arm.",
      "tips": "This is an exercise which can help you strengthen the muscles of the Rotator Cuff, which support your shoulder.",
      "warning": "",
      "id": 27,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1274_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1271_0_thumb.jpg",
      "title": "One Arm Flat Bench Flys",
      "videos": "",
      "Sort": "This exercise is similar to a Fly done with two dumbbells. This will help build strength in your rotator cuff and shoulder muscles.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1271_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Lie on a flat bench with your free hand holding the bench.  Grasp the dumbbell in your other hand and with your forearm parallel to the floor raise your arm in an arc the middle of your chest.  Once the dumbbell is at the middle of your chest line, slowly lower is along the same path to starting position.",
      "tips": "A helpful image is to think of giving yourself a one harmed hug.",
      "warning": "",
      "id": 28,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1271_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1272_0_thumb.jpg",
      "title": "One Arm Floor Press",
      "videos": "",
      "Sort": "This is a good exercise to build the strength and coordination needed for weight training. This exercise is best done with a partner.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1272_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"",
      "steps": "Lie flat on your back with your knees bent and your feet firmly on the floor.  Draw in your abs and contract your lats, and glutes.  Have your partner hand you the bar and with your bicep parallel to the floor lift extend your arm fully so it is straight.  Return to the starting position.  Complete reps and switch arms.",
      "tips": "",
      "warning": "",
      "id": 29,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1272_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1270_0_thumb.jpg",
      "title": "One Armed Biased Push-Up",
      "videos": "",
      "Sort": "This is an advanced form of Push Up, which also targets the Core muscles. Core exercises strengthen the abdominal and back muscles.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1270_0.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Arrange the dome so that as you begin the exercise, one hand on the Dome and the other on the floor.  Place the Dome flat side down on the floor.  Kneel on the floor with your arms fully extended on the dome, and body straight.  Keeping your abs drawn in and your body straight, lower your chest to the Dome.  Pause for a moment and then return to starting position.",
      "tips": "This is a difficult exercise to master. Beginners may want to start on your knees with your feet off the ground so you are rocking into the Push Up.",
      "warning": "",
      "id": 30,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1270_1.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1268_0_thumb.jpg",
      "title": "Push Up With Feet on Exercise Ball",
      "videos": "",
      "Sort": "This is similar to the standard Push Up except using an Exercise Ball forces you to engage the muscle of your core (Rectus Abdominis, Transverse Abdominis, and the Obliques.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1268_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Place your feet and shins flat on an Exercise Ball.  Place your arms in front of you at shoulder width apart, place your hands under your arms and press up from the ground until your arms are fully extended.  Pause at the top for a moment and steady your balance.  Slowly return to the starting position.",
      "tips": "Choose the right size ball for you. You should be able to fully extend your arms in a push up and be level with your feet on the ball.",
      "warning": "",
      "id": 31,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1268_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1267_0_thumb.jpg",
      "title": "Push-Ups",
      "videos": "",
      "Sort": "Push ups are a body weight only exercise with an action similar to the bench press.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1267_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"",
      "tipname":"",
      "steps": "",
      "tips": "",
      "warning": "",
      "id": 32,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1267_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/user/23676.jpg",
      "title": "Ring Push-Ups",
      "video":" Video",
      "photo":"Photo",
      "videos": "https://www.youtube.com/embed/m8GZlHJulc8",
      "Sort": "The push-up is a staple body weight exercise that almost everyone is familiar with. Adding gymnastic rings into the mix suspends your hands above ground and the independent movement of the rings makes the exercise much more difficult to control, adding an injection of intensity to the exercise.",
      "bigImg": "https://www.gymwolf.com/images/exercises/user/23676.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"",
      "steps": "1. Adjust the height of the rings appropriate for your fitness level (the lower the rings the more difficult the exercise).  2. Grip the rings, keep your body straight and your legs fully extended behind you.  3. Slowly lower yourself down towards the floor.  4. Pause at the bottom of the exercise then push yourself back up to the starting position. Do not lock out your elbows to maintain tension throughout the muscles during the exercise.  5. Repeat.",
      "tips": "",
      "warning": "",
      "id": 33,
      // "bigImg1": "",
     
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1266_0_thumb.jpg",
      "title": "Smith Machine Bench Press",
      "videos": "",
      "Sort": "This is the same exercise as a Bench Press but using the Smith Machine allows for greater control of the bar throughout the exercise.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1266_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Place a flat bench in the middle of the Smith Machine, with the bar in line with the middle of your chest.  Lying on the bench, grasp the bar at shoulder width apart.  Unlatch the bar and slowly lower the bar to your chest.  Extend your arms fully and raise the bar to the starting position.",
      "tips": "Keep your back flat on the bench throughout the exercises. The Smith Machine is a good tool for beginners to learn to use free weights safely.",
      "warning": "",
      "id": 34,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1266_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1265_0_thumb.jpg",
      "title": "Straight Arm Pullover",
      "videos": "",
      "Sort": "This is an exercise to strengthen the muscles of the shoulder and the rotator cuff.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1265_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"",
      "steps": "Lie on a flat bench with your feet flat on the floor and your head at the end of the bench.  Grasp a dumbbell and raise it over your chest.  Keeping your elbows as straight as possible, lower the weight in an arc over your head and as low to the ground as possible with out any pain.  Return to starting position.",
      "tips": "",
      "warning": "",
      "id": 35,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1265_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1262_0_thumb.jpg",
      "title": "Wide Grip Bench Press",
      "videos": "",
      "Sort": "This is an exercise for the Pectoral (Chest) muscles. It uses a wider grip that focuses on the outer portion of the chest.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1262_0.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"",
      "steps": "Lie flat on a bench with your feet flat on the floor.  Place your hands wider than shoulder width apart on the bar and lift it off the rack, this is starting position.  Bring the bar over your chest and lower it till it is just above your body.  Extend your arms upward and raise the bar straight up.  Pause for a moment and with slow controlled movement, return the bar to starting position.",
      "tips": "Keep your abs drawn in and your back flat on the bench throughout this exercise.",
      "warning": "",
      "id": 36,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1262_1.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1261_0_thumb.jpg",
      "title": "Wide Grip Decline Bench Press",
      "videos": "",
      "Sort": "This is an exercise for the Pectoral (Chest) muscles. It uses a wider grip and focuses on the outer portion of the chest. Decline Bench Presses work the lower portion of the Pectoral muscles.",
      "bigImg": "https://www.gymwolf.com/images/exercises/1261_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Lie on a decline bench with your head lower than your feet.  Place your hands wider than shoulder width apart on the bar and lift it off the rack.  Bring the bar over your chest and lower it till it is just above the lower portion of your chest, this is starting position.  Extend your arms upward and raise the bar straight up.  Pause for a moment and then lower the bar to starting position.",
      "tips": "Keep your abs drawn in and your back flat on the bench throughout this exercise.",
      "warning": "",
      "id": 37,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1261_0.jpg",
      "video":"",
      "photo":"",
    },
    {
      "smallImg": "https://www.gymwolf.com/images/exercises/1277_0_thumb.jpg",
      "title": "Wide Grip Decline Pullover",
      "videos": "",
      "Sort": "This is an advanced exercise for the pectoral muscles (Chest). Similar to the Wide Grip Pullover, it targets muscles of the chest, shoulders and works the core muscles (abdominals).",
      "bigImg": "https://www.gymwolf.com/images/exercises/1277_1.jpg",
      "muscleGroup": "Chest",
      "stepname":"Steps",
      "tipname":"Tips",
      "steps": "Lie on a decline bench with your feet higher than your head/  Grasp the barbell with an extra wide grip (your hands near the plates) and starting at youre your upper thighs raise the barbell in an arc over your head towards the floor.  Slowly return the barbell to starting position on your thighs.",
      "tips": "For an added benefit, squeeze the bar as though you were pushing the ends together this will help give additional muscle contraction.  Do not go beyond a normal range of motion  This exercise should be avoided if you are experiencing shoulder injury or pain.",
      "warning": "",
      "id": 38,
      "bigImg1": "https://www.gymwolf.com/images/exercises/1277_0.jpg",
      "video":"",
      "photo":"",
    }
  ]
    
  displaydata(chest)

  function displaydata(chest){
    let container=document.getElementById("data")

    chest.forEach(function(el){
         let div=document.createElement("div")
         let div1=document.createElement("div")

         div1.setAttribute("id","div1")
         let div2=document.createElement("div")
         div2.setAttribute("id","div2")
         let div3=document.createElement("div")
         div3.setAttribute("id","div3")
         let img=document.createElement("img")
         img.src=el.smallImg
         div1.append(img)
         
         let title=document.createElement("p")
         title.innerText=el.title
         title.setAttribute("id","title")
         title.addEventListener("click",function(){
            adddata(el)
         })

         let sort=document.createElement("p")
         sort.innerText=el.Sort
         sort.setAttribute("id","sort")
        div3.append(div1)
         div2.append(title,sort)
         div.append(div3,div2)
         container.append(div)
    });
    function adddata(el){
      console.log(el.id)
      if(el.id==33){
        window.location.href="video.html"
        localStorage.setItem("data",JSON.stringify(el))
      }else{
        localStorage.setItem("data",JSON.stringify(el))
        window.location.href="chestobj.html"
      }
     
    }
  }